# Perform data exploration for data science

Use the code in this notebook to perform data exploration for data science.

In [1]:
# Azure storage access info for open dataset diabetes
blob_account_name = "azureopendatastorage"
blob_container_name = "ojsales-simulatedcontainer"
blob_relative_path = "oj_sales_data"
blob_sas_token = r"" # Blank since container is Anonymous access

# Set Spark config to access  blob storage
wasbs_path = f"wasbs://%s@%s.blob.core.windows.net/%s" % (blob_container_name, blob_account_name, blob_relative_path)
spark.conf.set("fs.azure.sas.%s.%s.blob.core.windows.net" % (blob_container_name, blob_account_name), blob_sas_token)
print("Remote blob path: " + wasbs_path)

# Spark reads csv
df = spark.read.csv(wasbs_path, header=True)

StatementMeta(, c04eeef3-4242-4f86-8c71-cf0dfdd0aa62, 3, Finished, Available)

Remote blob path: wasbs://ojsales-simulatedcontainer@azureopendatastorage.blob.core.windows.net/oj_sales_data

In [2]:
import pandas as pd

df = df.toPandas()
df = df.sample(n=500, random_state=1)

df['WeekStarting'] = pd.to_datetime(df['WeekStarting'])
df['Quantity'] = df['Quantity'].astype('int')
df['Advert'] = df['Advert'].astype('int')
df['Price'] = df['Price'].astype('float')
df['Revenue'] = df['Revenue'].astype('float')

df = df.reset_index(drop=True)
df.head(4)

StatementMeta(, c04eeef3-4242-4f86-8c71-cf0dfdd0aa62, 4, Finished, Available)

  WeekStarting Store        Brand  Quantity  Advert  Price   Revenue
0   1991-10-17   947  minute.maid     13306       1   2.42  32200.52
1   1992-03-26  1293    dominicks     18596       1   1.94  36076.24
2   1991-08-15  2278    dominicks     17457       1   2.14  37357.98
3   1992-09-03  2175    tropicana      9652       1   2.07  19979.64

In [3]:
# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Replace all instances of "." with " " in column: 'Brand'
    df['Brand'] = df['Brand'].str.replace(".", " ", case=False, regex=False)
    # Capitalize the first character in column: 'Brand'
    df['Brand'] = df['Brand'].str.capitalize()
    return df

df_clean = clean_data(df)
df_clean.head()

StatementMeta(, c04eeef3-4242-4f86-8c71-cf0dfdd0aa62, 37, Finished, Available)

  WeekStarting Store        Brand  Quantity  Advert  Price   Revenue
0   1991-10-17   947  Minute maid     13306       1   2.42  32200.52
1   1992-03-26  1293    Dominicks     18596       1   1.94  36076.24
2   1991-08-15  2278    Dominicks     17457       1   2.14  37357.98
3   1992-09-03  2175    Tropicana      9652       1   2.07  19979.64
4   1991-06-27  3372    Dominicks     16587       1   2.26  37486.62

In [4]:
df['Brand'].unique()

StatementMeta(, c04eeef3-4242-4f86-8c71-cf0dfdd0aa62, 38, Finished, Available)

array(['Minute maid', 'Dominicks', 'Tropicana'], dtype=object)

In [5]:
def clean_data(df):    
   # Replace all instances of "." with " " in column: 'Brand'    
   df['Brand'] = df['Brand'].str.replace(".", " ", case=False, regex=False)    
   # Capitalize the first character in column: 'Brand'    
   df['Brand'] = df['Brand'].str.title()

   # Performed 1 aggregation grouped on column: 'Brand'    
   df = df.groupby(['Brand']).agg(Revenue_mean=('Revenue', 'mean')).reset_index()    

   return df    

df = clean_data(df)

StatementMeta(, c04eeef3-4242-4f86-8c71-cf0dfdd0aa62, 122, Finished, Available)

In [6]:
print(df)

StatementMeta(, c04eeef3-4242-4f86-8c71-cf0dfdd0aa62, 123, Finished, Available)

         Brand  Revenue_mean
0    Dominicks  33206.330958
1  Minute Maid  33532.999632
2    Tropicana  33637.863412